import type { DemoArtifactTemplate } from "../../demo";

type Props = {
  artifact: DemoArtifactTemplate;
  status: "pending" | "approved" | "rejected";
  onViewInSandbox?: () => void;
  onViewDrawing?: () => void;
  onViewDocument?: () => void;
  onReview?: () => void;
};

export default function ArtifactCard({ artifact, status, onViewInSandbox, onViewDrawing, onViewDocument, onReview }: Props) {
  const typeIcon = () => {
    switch (artifact.type) {
      case "CODE": return (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline></svg>
      );
      case "CAD": return (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>
      );
      default: return (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline></svg>
      );
    }
  };

  const handleOpenPdf = () => {
    window.open(`/documents/${artifact.name}`, "_blank", "noopener,noreferrer");
  };

  return (
    <div className="p-4 bg-white border border-slate-200 rounded-xl shadow-sm">
      <div className="text-[10px] font-bold text-slate-500 tracking-wider mb-3 flex items-center gap-2">
        <span className="w-1.5 h-1.5 rounded-full bg-teal-500"></span>
        ARTIFACT GENERATED
      </div>
      
      <div className="flex flex-col md:flex-row md:items-start justify-between w-full gap-4">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-lg bg-teal-50 flex items-center justify-center text-teal-600 shadow-sm border border-teal-100 shrink-0 mt-1">
            {typeIcon()}
          </div>
          <div>
            <div className="text-sm font-semibold text-slate-800 flex items-center gap-2">
              📄 {artifact.name}
            </div>
            
            <div className="grid grid-cols-2 gap-x-6 gap-y-2 mt-3">
              <div>
                <div className="text-[10px] font-bold text-slate-400 uppercase">Type</div>
                <div className="text-xs font-medium text-slate-700">{artifact.type} Document</div>
              </div>
              <div>
                <div className="text-[10px] font-bold text-slate-400 uppercase">Generated by</div>
                <div className="text-xs font-medium text-slate-700">{artifact.createdBy}</div>
              </div>
              <div>
                <div className="text-[10px] font-bold text-slate-400 uppercase">Sources</div>
                <div className="text-xs font-medium text-slate-700">3 internal documents</div>
              </div>
              <div>
                <div className="text-[10px] font-bold text-slate-400 uppercase">Classification</div>
                <div className="text-xs font-medium text-slate-700">
                  <span className={`px-1.5 py-0.5 rounded-md ${
                    artifact.classification === "RESTRICTED" ? "bg-red-50 text-red-600" :
                    artifact.classification === "CONFIDENTIAL" ? "bg-amber-50 text-amber-600" :
                    "bg-blue-50 text-blue-600"
                  }`}>
                    🔒 {artifact.classification}
                  </span>
                </div>
              </div>
            </div>
            
            <div className="flex items-center gap-2 mt-4">
              <span className="text-[10px] font-bold text-slate-400 uppercase">Status:</span>
              <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-100 flex items-center gap-1">
                <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><polyline points="20 6 9 17 4 12"></polyline></svg>
                GENERATED
              </span>
            </div>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex flex-col gap-2 shrink-0 md:w-40">
          {artifact.type === "CODE" && onViewInSandbox && (
            <button
              onClick={onViewInSandbox}
              className="w-full flex items-center justify-center gap-1.5 text-xs px-3 py-2 bg-slate-800 hover:bg-slate-900 text-white font-medium rounded-lg transition-colors shadow-sm"
            >
              Open in Coding Workspace
            </button>
          )}
          {artifact.type === "CAD" && onViewDrawing && (
            <button onClick={onViewDrawing} className="w-full flex items-center justify-center gap-1.5 text-xs px-3 py-2 bg-slate-800 hover:bg-slate-900 text-white font-medium rounded-lg transition-colors shadow-sm">
              View Drawing
            </button>
          )}
          {(artifact.type === "PDF" || artifact.type === "DOCX" || artifact.type === "CSV" || artifact.type === "XLSX") && (
            <>
              {onViewDocument && (
                <button onClick={onViewDocument} className="w-full flex items-center justify-center gap-1.5 text-xs px-3 py-2 bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 font-medium rounded-lg transition-colors shadow-sm">
                  Preview
                </button>
              )}
              {artifact.type === "PDF" && (
                <button onClick={handleOpenPdf} className="w-full flex items-center justify-center gap-1.5 text-xs px-3 py-2 bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 font-medium rounded-lg transition-colors shadow-sm">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline></svg>
                  Open PDF
                </button>
              )}
              {onReview && (
                <button onClick={onReview} className="w-full flex items-center justify-center gap-1.5 text-xs px-3 py-2 bg-teal-600 hover:bg-teal-700 text-white font-medium rounded-lg transition-colors shadow-sm">
                  Review
                </button>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
